- name: Deploy the war file 
  hosts: all 
  become: yes 
  vars:
    TOMCAT_LOC: /home/student/apache-tomcat-8.5.38
  tasks:
    - name: Check a directory exists or not 
      shell: ls -ld {{TOMCAT_LOC}}

    - name: Find old file 
      find:
        find: 
        paths: "{{TOMCATDIR}}/webapps"
        file_type: any
      register: out 
