- name: Deploy the war file 
  hosts: all 
  become: yes 
  vars:
    TOMCAT_LOC: /home/student/apache-tomcat-8.5.38
  tasks:
    - name: Stop Api Service 
      service:
        name: studentapi 
        state: stopped 

    - name: Check a directory exists or not 
      shell: ls -ld {{TOMCAT_LOC}}

    - name: Find old file 
      find: 
        paths: [ "{{TOMCAT_LOC}}/webapps" ,"/home/student/API"]
        file_type: any
      register: out 

    - name: Remove the old webapps 
      file:
        path: "{{item.path}}"
        state: absent 
      loop: "{{out.files}}"

    - name: Install python pip package 
      yum:
        name: python2-pip 
        state: installed 

    - name: Install python boto modules 
      pip:
        name: "{{item}}"
      loop:
        - botocore
        - boto3

    - name: Download UI War file 
      aws_s3:
        bucket: terraform-batch37
        object: /artifacts/studentui.war
        dest: "{{TOMCAT_LOC}}/webapps/student.war"
        mode: get
      become_user: student
    
    
    - name: Download API war file 
      aws_s3:
        bucket: terraform-batch37
        object: /artifacts/studentapi.war
        dest: "/home/student/API/studentapi.war"
        mode: get
      become_user: student

    - name: Start API Service 
      
