- name: Deploy the war file 
  hosts: all 
  become: yes 
  vars:
    TOMCAT_LOC: /home/student/apache-tomcat-8.5.38
  tasks:
    - name: Check a directory exists or not 
      shell: ls -ld {{TOMCAT_LOC}}

    - name: Find old file 
      find: 
        paths: "{{TOMCAT_LOC}}/webapps"
        file_type: any
      register: out 

    - name: Remove the old webapps 
      file:
        path: "{{item.path}}"
        state: absent 
      loop: "{{out.files}}"


    - name: Find local war file 
      find: 
        paths: "{{WAR_LOC}}"
        file_type: file 
        patterns: "*.war"
      register: out 
      delegate_to: 127.0.0.1

    - debug: msg="{{out}}"
    #- name: Copy war file 
    #  copy:
    #    src: ../target/studentapp*.war
    #    dest: "{{TOMCAT_LOC}}/webapps/student.war"

    
